name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
#      - name: checkout repository
#        uses: actions/checkout@v4

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: |
          docker build -t lasithdev/civilink_project_management_api:${{github.sha}} .
          docker tag lasithdev/civilink_project_management_api:${{github.sha}} lasithdev/civilink_project_management_api:latest

      - name: Push Docker Image to Docker hub
        run: |
          docker push lasithdev/civilink_project_management_api:latest

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud components update

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials civilink-cluster --zone us-central1-c --project ${{ secrets.GCP_PROJECT }}
      - name: Update GKE Deployment
        run: |
          kubectl set image deployment/civilink_project_management civilink_project_management=lasithdev/project_management_api:latest -n development
          kubectl rollout restart deployment civilink_project_management -n development
